#
# HMCL pipeline configuration
#
name: hmcl

#
# feature processing
#

# minimum amount of total variance to be accounted for in PCA-projected versions
# of feature data
pca_scale: true
pca_min_variance: 0.95
