#
# HMCL pipeline configuration
#
name: hmcl

#
# feature processing
#

# function to use when aggregating feature data within gene sets
aggregation_func: median

# minimum amount of total variance to be accounted for in PCA-projected versions
# of feature data
pca_scale: true
pca_min_variance: 0.95
