#
# HMCL pipeline configuration
#
name: hmcl
version: 0.1

#
# feature processing
#

# minimum number of genes required for a gene set to be used for projecing
# feature data
gene_set_min_size: 5

# functions to use when aggregating feature data within gene sets
aggregation_funcs:
  rna: median
  cnv: mean
  var: sum

# minimum amount of total variance to be accounted for in PCA-projected versions
# of feature data
pca_scale: true
pca_min_variance: 0.95

#
# feature selection
#
feat_selection:
  rna:
    min_var_quantile: 0.25
    max_cor: 0.90
  cnv:
    min_var_quantile: 0.25
    max_cor: 0.95
  var:
    min_var_quantile: 0.25
    max_cor: 0.90
