#
# HMCL pipeline configuration
#
name: hmcl

#
# feature processing
#

# function to use when aggregating feature data within gene sets
aggregation_func: median

# minimum amount of total variance to be accounted for in PCA-projected versions
# of feature data
pca_scale: true
pca_min_variance: 0.95

#
# feature selection
#
feat_selection_min_var_quantile: 0.25
feat_selection_max_cor_rna: 0.90
feat_selection_max_cor_cnv: 0.95
feat_selection_max_cor_variatns: 0.90
