#!/bin/env Rscript
library(annotables)
library(tidyverse)
options(stringsAsFactors = FALSE)

exclude_cells <- c('KMS21BM_JCRB', 'Karpas417_ECACC', 'OCIMY1_PLB', 'OPM2_DSMZ')

# load raw gene-level (ensembl) counts
dat_grch37 <- read_tsv('/data/projects/nih/p3/exome_variants/exome_variants_by_gene_grch37.tsv')
dat_grch38 <- read_tsv('/data/projects/nih/p3/exome_variants/exome_variants_by_gene_grch38.tsv')

# drop outlier cell lines
dat_grch37 <- dat_grch37[, !colnames(dat_grch37) %in% exclude_cells]
dat_grch38 <- dat_grch38[, !colnames(dat_grch38) %in% exclude_cells]

# datasets were generated by different methods
#sum(dat_grch37[, -1])
# [1] 36314

#sum(dat_grch38[, -1])
# [1] 42368

# convert ensembl gene ids -> gene symbols
dat_grch37$symbol <- grch37$symbol[match(dat_grch37$ENSEMBL, grch37$ensgene)]
dat_grch38$symbol <- grch38$symbol[match(dat_grch38$ENSEMBL, grch38$ensgene)]

#table(is.na(dat_grch37$symbol))
# 
# FALSE 
#  9730 

#table(is.na(dat_grch38$symbol))
# 
# FALSE  TRUE 
#  9780    76 

# remove unmapped genes
dat_grch37 <- dat_grch37[!is.na(dat_grch37$symbol), ]
dat_grch38 <- dat_grch38[!is.na(dat_grch38$symbol), ]

#head(sort(table(dat_grch37$symbol), TRUE))
# 
#   NCR1   FCAR    GP6 MBOAT7 PRPF31  VSTM1 
#     16     10     10     10     10     10 

# average multi-mapped gene symbols
dat_grch37 <- dat_grch37 %>%
  select(-ENSEMBL) %>%
  group_by(symbol) %>%
  summarise_all(funs(mean))

dat_grch38 <- dat_grch38 %>%
  select(-ENSEMBL) %>%
  group_by(symbol) %>%
  summarise_all(funs(mean))

# drop any genes with zero variance
mask1 <- apply(dat_grch37[, -1], 1, var) > 0
mask2 <- apply(dat_grch38[, -1], 1, var) > 0

#table(mask1)
# mask1
# FALSE  TRUE 
#     3  9712 

#table(mask2)
# mask2
# FALSE  TRUE 
#     2  9008 

dat_grch37 <- dat_grch37[mask1, ]
dat_grch38 <- dat_grch38[mask2, ]

write_tsv(dat_grch37, '/data/projects/nih/p3-models/data/raw/features/cnv/exome_variants_by_gene_grch37.tsv')
write_tsv(dat_grch37, '/data/projects/nih/p3-models/data/raw/features/cnv/exome_variants_by_gene_grch38.tsv')

