################################################################################
#
# GDSC pipeline configuration
#
################################################################################
name: gdsc
version: 0.2
debug: true

#
# Computational resources
# 

# per-rule thread usage for parellelized rules
num_threads:
  feature_selection: 16
  train_model: 16

#
# Feature input data
#
features:
  rna: 'rna/GDSC_rna.tsv.gz'
  cnv: 'cnv/GDSC_cnv.tsv.gz'
  var: 'var/GDSC_var.tsv.gz'

#
# Cross validation
#

# parameters to use for outer repeated cross validation
cross_validation:
  num_splits: 5
  num_repeats: 3
  random_seed: 801372

#
# Model training
#
model:
  method: 'random_forest'
  num_trees: 25000

#
# Pathway aggregation
#

# minimum number of genes required for a gene set to be used for projecing
# feature data
gene_set_projection:
  enabled: true
  gene_set_min_size: 5
  aggregation_funcs:
    rna: median
    cnv: mean
    var: sum

#
# Dimension reduction (individual datasets)
#
dimension_reduction_early:
  enabled: false
  method: pca
  scale: true
  min_variance: 0.95

#
# Dimension reduction (combined dataset)
#
dimension_reduction_late:
  enabled: false
  method: pls

#
# Feature filtering
# 
# As an early step, some basic unsupervised feature filtering can be performed
# independently on each feature data type (rna, cnv, var).
#
# The type of filtering performed include:
#
#  1. Minimum variance
#  2. Maximum correlation
#
# For variance-based filtering, a quantile ranging from 0-1 may be specified and all
# features with variances lower than that quantile will be excluded. For example, if a
# min_var_quantile values of "0.4" is specified, the bottom 40% of features, in terms of
# their variances, will be dropped.
#
# For correlation-based filtering, a maximum pearson correlation score may be specified
# and, for each pair of features with a correlation value above the specified cutoff,
# one of the two features will be removed at random.
#
feature_filtering:
  rna:
    min_var_quantile: 0.25
    max_cor: 0.90
  cnv:
    min_var_quantile: 0.25
    max_cor: 0.95
  var:
    min_var_quantile: 0
    max_cor: 1

=======
#
# Feature selection
# 
# Once the feature data has been filtered and combined into a single training set, a
# more sophisticated supervised feature selection approach may be applied.
# 
# Feature selection is performed using the Boruta wrapper method  with the Ranger
# implementation of random forests.
# 
feature_selection:
  method: rfe
  fallback: none
  min_features: 100
  max_features: 1000
  num_trees: 25000
  mtry: 4

