#
# GDSC pipeline configuration
#
name: gdsc
version: 0.1
debug: true

#
# feature input data
#
features:
  rna: 'rna/GDSC_rna.tsv.gz'
  cnv: 'cnv/GDSC_cnv.tsv.gz'
  var: 'var/GDSC_var.tsv.gz'

#
# cross validation
# 
# parameters to use for outer repeated cross validation
#
cross_validation:
  num_splits: 5
  num_repeats: 3
  random_seed: 801372

#
# feature processing
#

# minimum number of genes required for a gene set to be used for projecing
# feature data
gene_set_projection:
  enabled: true
  gene_set_min_size: 5
  aggregation_funcs:
    rna: median
    cnv: mean
    var: sum

# minimum amount of total variance to be accounted for in PCA-projected versions
# of feature data
pca_projection:
  enabled: false
  scale: true
  min_variance: 0.95

#
# feature filtering
#
feature_filtering:
  rna:
    min_var_quantile: 0.25
    max_cor: 0.90
  cnv:
    min_var_quantile: 0.25
    max_cor: 0.95
  var:
    min_var_quantile: 0
    max_cor: 1

#
# Feature selection
# 
# Once the feature data has been filtered and combined into a single training set, a
# more sophisticated supervised feature selection approach may be applied.
# 
# Feature selection is performed using the Boruta wrapper method  with the Ranger
# implementation of random forests.
# 
feature_selection:
  method: boruta
  fallback: rfe
  min_features: 5
  max_features: 1000
  num_trees: 25000
  mtry: 4

