################################################################################
#
# HMCL pipeline configuration
#
################################################################################
name: hmcl
version: 0.2
debug: true
output: '/data/zhangamx/p3-model-iteration/'   # larger directory for output storage


#
# Computational resources
# 

# per-rule thread usage for parellelized rules
num_threads:
  feature_selection: 1
  train_model: 4
  filter_features: 12
#
# Feature input data
# 
features:
  rna: 'rna/rnaseq_grch38_featurecounts_cpm.tsv.gz'
  cnv: 'cnv/cnv_rcgh_gene_table_log2ratio_hg38.tsv.gz'
  var: 'var/exome_variants_by_gene_grch38.tsv.gz'

#
# Cross validation
#

# parameters to use for outer repeated cross validation
cross_validation:
  num_splits: 1
  num_repeats: 1
  min_group_size: 5
  random_seed: 801372

#
# Model specification
#
model_combinations:
  feature_aggregation:
    - gene_sets
    - raw
  feature_selection:
    - distance
  dimension_reduction:
    - mofa
  models:
    - linear
    - bimixture
    - horseshoe


#
# Feature aggregation
#
gene_set_aggregation:
  gene_set_min_size: 5
  aggregation_funcs:
    rna: median
    cnv: mean
    var: sum

#
# Dimension reduction
#
dimension_reduction:
  mofa:
    modeloptions:
      numFactors: 20
      sparsity: true
    trainoptions:
      maxiter: 3000
      tolerance: 1.0
      seed: 23827
      # DropFactorThreshold: 0.01

#
# Feature filtering
# 
# As an early step, some basic unsupervised feature filtering can be performed
# independently on each feature data type (rna, cnv, var).
#
# The type of filtering performed include:
#
#  1. Minimum variance
#  2. Maximum correlation
#
# For variance-based filtering, a quantile ranging from 0-1 may be specified and all
# features with variances lower than that quantile will be excluded. For example, if a
# min_var_quantile values of "0.4" is specified, the bottom 40% of features, in terms of
# their variances, will be dropped.
#
# For correlation-based filtering, a maximum pearson correlation score may be specified
# and, for each pair of features with a correlation value above the specified cutoff,
# one of the two features will be removed at random.
#
feature_filtering:
  rna:
    min_var_quantile: 0.25
    max_cor: 0.90
  cnv:
    min_var_quantile: 0.25
    max_cor: 0.95
  var:
    min_var_quantile: 0.25
    max_cor: 0.90

#
# Feature selection
# 
# Once the feature data has been filtered and combined into a single training set, a
# more sophisticated supervised feature selection approach may be applied.
# 
# Feature selection is performed using the Boruta wrapper method  with the Ranger
# implementation of random forests.
# 
feature_selection:
  method: none
  fallback: none
  min_features: 100
  max_features: 1000
  num_trees: 25000
  mtry: 4

